Add solutions for forms and deep-vue tasks
js-tasks-ru/vue-20201022_constantine0 pull request #9
Opened 2020-11-27 19:24 UTC by ConstantineUA

2020-11-27 20:19 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
MeetupAgendaItemForm
+ MeetupAgendaItemForm должен иметь обязательный параметр agendaItem
+ MeetupAgendaItemForm должен выводить поля доклада с корректными значениями по умолчанию
+ MeetupAgendaItemForm должен порождать событие remove при клике на кнопку удаления
+ MeetupAgendaItemForm должен выводить все поля для типа other
+ MeetupAgendaItemForm должен выводить все поля для типа talk
+ MeetupAgendaItemForm должен выводить все поля для типа registration
+ MeetupAgendaItemForm должен выводить все поля для типа opening
+ MeetupAgendaItemForm должен выводить все поля для типа break
+ MeetupAgendaItemForm должен выводить все поля для типа coffee
+ MeetupAgendaItemForm должен выводить все поля для типа closing
+ MeetupAgendaItemForm должен выводить все поля для типа afterparty
+ MeetupAgendaItemForm должен синхронизировать параметр agendaItem после изменения значения в форме доклада
+ MeetupAgendaItemForm должен увеличивать время окончания с 10:00 до 11:00 при увеличении времени начала с 05:00 до 06:00
+ MeetupAgendaItemForm должен уменьшать время окончания с 10:00 до 09:00 при уменьшении времени начала с 05:00 до 04:00
+ MeetupAgendaItemForm должен увеличивать время окончания с 10:00 до 03:00 при увеличении времени начала с 05:00 до 22:00 при переходе через полночь
+ MeetupAgendaItemForm должен увеличивать время окончания с 11:00 до 12:00 при увеличении времени начала с 05:00 до 06:00 после установки времени окончания в 11:00
+ MeetupAgendaItemForm должен увеличивать время окончания с 02:00 до 03:00 при увеличении времени начала с 05:00 до 06:00 после установки времени окончания в 02:00
```
```diff
Buttons
+ Компонент BaseButton должен иметь логический параметр block
+ Компонент BaseButton должен иметь необязательный строковый параметр tag со значением button по умолчанию
+ Параметр tag у BaseButton должен иметь валидатор
+ Компонент BaseButton должен рендерить своё содержимое
+ Компонент BaseButton должен иметь класс button_block только с параметром block
+ Компонент BaseButton должен рендерить ссылку с tag=a c переданными href и target
+ Компонент BaseButton должен обрабатывать нативный клик
+ Компонент PrimaryButton должен рендерить компонент BaseButton с теми же параметрами, обработчиками событий и содержимым
+ Компонент PrimaryButton должен рендерить кнопку с классом button_primary
+ Компонент SecondaryButton должен рендерить компонент BaseButton с теми же параметрами, обработчиками событий и содержимым
+ Компонент SecondaryButton должен рендерить кнопку с классом button_secondary
+ Компонент DangerButton должен рендерить компонент BaseButton с теми же параметрами, обработчиками событий и содержимым
+ Компонент DangerButton должен рендерить кнопку с классом button_danger
```

Добавляю преподавателя (@ShGKme) для код-ревью, посмотрим что он скажет :)

2020-11-27 21:07 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2020-12-03 03:23 UTC, ShGKme requested changes
Требуется небольшое исправление в BaseButton.

2020-12-03 03:23 UTC, ShGKme commented on 07-forms/03-MeetupAgendaItemForm/components/MeetupAgendaItemForm.vue
> +    "localAgendaItem.startsAt"(newValue, oldValue) {
Такой синтаксис отслеживания не будет работать во Vue 3. Вместо этого потребуется создавать вычисляемое свойство, либо следить за всем объектом.

2020-12-03 03:23 UTC, ShGKme commented on 06-deep-vue/01-Buttons/components/BaseButton.vue
> +  </component>
Атрибуты будут переброшены на компонент в component за счёт наследования атрибутов.
Однако входные параметры не работают, и, если в качестве tag будет компонент, он не получит входных параметров, установленных на component. Требуется явно указывать `v-bind="$attrs"`.

Пример: https://repl.it/@ShGKme/Vue-Inherit-Props
Здесь передаётся `href` на `a` внутри `router-link`, но не передаётся параметр `to` на него же.

2020-12-04 13:41 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2020-12-04 17:06 UTC, ShGKme approved these changes
Принято 👍

2020-12-04 17:12 UTC, merged